namespace Griesoft.OrchardCore.CookieConsent.Models;

/// <summary>
/// A single consent decision reported by the client-side banner.
/// </summary>
public class ConsentRecord
{
    /// <summary>
    /// The anonymous consent id generated by the banner (stored in the consent cookie).
    /// </summary>
    public string? ConsentId { get; set; }

    /// <summary>
    /// How consent was given: "all", "necessary" or "custom".
    /// </summary>
    public string? AcceptType { get; set; }

    /// <summary>
    /// The categories the visitor accepted.
    /// </summary>
    public string[] AcceptedCategories { get; set; } = [];

    /// <summary>
    /// The categories the visitor rejected.
    /// </summary>
    public string[] RejectedCategories { get; set; } = [];

    /// <summary>
    /// Server-side UTC timestamp of when the record was received.
    /// </summary>
    public DateTime RecordedUtc { get; set; }
}
